---
- name: Configure Elk VM with Docker
  hosts: elk
  remote_user: azdmin
  become: true
  tasks:

    - name: Install docker.io
      apt:
           name: docker.io
           update_cache: yes
           state: present

    - name: Install python3-pip
      apt:
           name: python3-pip
           state: present

    - name: Install Docker
      pip:
           name: docker
           state: present

    - name: Increase Memory
      sysctl:
           name: vm.max_map_count
           value: "262144"
           state: present
           reload: yes

    - name: Download & Launch Docker Container
      docker_container:
           name: elk-stack
           image: sebp/elk:761
           state: started
           restart_policy: always
           published_ports:
               - "5601:5601"
               - "9200:9200"
               - "5044:5044"

    - name: Start Docker
      systemd:
           name: docker
           enabled: yes
